services:
  - type: web
    name: yahayatravelandtrade
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 22
