/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestEnvRouteImport } from './routes/test-env'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminDebugRouteImport } from './routes/admin/debug'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminWebsiteRouteImport } from './routes/admin/website'
import { Route as AdminWebsiteCompanyInfoRouteImport } from './routes/admin/website/company-info'
import { Route as AdminWebsiteFaqsRouteImport } from './routes/admin/website/faqs'
import { Route as AdminWebsiteGalleryRouteImport } from './routes/admin/website/gallery'
import { Route as AdminWebsiteHomepageRouteImport } from './routes/admin/website/homepage'
import { Route as AdminWebsiteSeoRouteImport } from './routes/admin/website/seo'
import { Route as AdminWebsiteServicesRouteImport } from './routes/admin/website/services'
import { Route as AdminWebsiteTestimonialsRouteImport } from './routes/admin/website/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestEnvRoute = TestEnvRouteImport.update({
  id: '/test-env',
  path: '/test-env',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDebugRoute = AdminDebugRouteImport.update({
  id: '/admin/debug',
  path: '/admin/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/admin/website',
  path: '/admin/website',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteCompanyInfoRoute = AdminWebsiteCompanyInfoRouteImport.update({
  id: '/company-info',
  path: '/company-info',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteFaqsRoute = AdminWebsiteFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteGalleryRoute = AdminWebsiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteHomepageRoute = AdminWebsiteHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteSeoRoute = AdminWebsiteSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteServicesRoute = AdminWebsiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminWebsiteRoute,
} as any)
const AdminWebsiteTestimonialsRoute =
  AdminWebsiteTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AdminWebsiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/test-env': typeof TestEnvRoute
  '/trade': typeof TradeRoute
  '/travel': typeof TravelRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/website/company-info': typeof AdminWebsiteCompanyInfoRoute
  '/admin/website/faqs': typeof AdminWebsiteFaqsRoute
  '/admin/website/gallery': typeof AdminWebsiteGalleryRoute
  '/admin/website/homepage': typeof AdminWebsiteHomepageRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/website/services': typeof AdminWebsiteServicesRoute
  '/admin/website/testimonials': typeof AdminWebsiteTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/test-env': typeof TestEnvRoute
  '/trade': typeof TradeRoute
  '/travel': typeof TravelRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/website/company-info': typeof AdminWebsiteCompanyInfoRoute
  '/admin/website/faqs': typeof AdminWebsiteFaqsRoute
  '/admin/website/gallery': typeof AdminWebsiteGalleryRoute
  '/admin/website/homepage': typeof AdminWebsiteHomepageRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/website/services': typeof AdminWebsiteServicesRoute
  '/admin/website/testimonials': typeof AdminWebsiteTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/test-env': typeof TestEnvRoute
  '/trade': typeof TradeRoute
  '/travel': typeof TravelRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/debug': typeof AdminDebugRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/website': typeof AdminWebsiteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/website/company-info': typeof AdminWebsiteCompanyInfoRoute
  '/admin/website/faqs': typeof AdminWebsiteFaqsRoute
  '/admin/website/gallery': typeof AdminWebsiteGalleryRoute
  '/admin/website/homepage': typeof AdminWebsiteHomepageRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/website/services': typeof AdminWebsiteServicesRoute
  '/admin/website/testimonials': typeof AdminWebsiteTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/privacy'
    | '/quote'
    | '/terms'
    | '/test-env'
    | '/trade'
    | '/travel'
    | '/admin/clients'
    | '/admin/debug'
    | '/admin/enquiries'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/media'
    | '/admin/quotes'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/website'
    | '/admin/'
    | '/admin/website/company-info'
    | '/admin/website/faqs'
    | '/admin/website/gallery'
    | '/admin/website/homepage'
    | '/admin/website/seo'
    | '/admin/website/services'
    | '/admin/website/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/privacy'
    | '/quote'
    | '/terms'
    | '/test-env'
    | '/trade'
    | '/travel'
    | '/admin/clients'
    | '/admin/debug'
    | '/admin/enquiries'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/media'
    | '/admin/quotes'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/website'
    | '/admin'
    | '/admin/website/company-info'
    | '/admin/website/faqs'
    | '/admin/website/gallery'
    | '/admin/website/homepage'
    | '/admin/website/seo'
    | '/admin/website/services'
    | '/admin/website/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/privacy'
    | '/quote'
    | '/terms'
    | '/test-env'
    | '/trade'
    | '/travel'
    | '/admin/clients'
    | '/admin/debug'
    | '/admin/enquiries'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/media'
    | '/admin/quotes'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/website'
    | '/admin/'
    | '/admin/website/company-info'
    | '/admin/website/faqs'
    | '/admin/website/gallery'
    | '/admin/website/homepage'
    | '/admin/website/seo'
    | '/admin/website/services'
    | '/admin/website/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HealthRoute: typeof HealthRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  TermsRoute: typeof TermsRoute
  TestEnvRoute: typeof TestEnvRoute
  TradeRoute: typeof TradeRoute
  TravelRoute: typeof TravelRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDebugRoute: typeof AdminDebugRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminWebsiteRoute: typeof AdminWebsiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-env': {
      id: '/test-env'
      path: '/test-env'
      fullPath: '/test-env'
      preLoaderRoute: typeof TestEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debug': {
      id: '/admin/debug'
      path: '/admin/debug'
      fullPath: '/admin/debug'
      preLoaderRoute: typeof AdminDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/admin/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/company-info': {
      id: '/admin/website/company-info'
      path: '/company-info'
      fullPath: '/admin/website/company-info'
      preLoaderRoute: typeof AdminWebsiteCompanyInfoRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/faqs': {
      id: '/admin/website/faqs'
      path: '/faqs'
      fullPath: '/admin/website/faqs'
      preLoaderRoute: typeof AdminWebsiteFaqsRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/gallery': {
      id: '/admin/website/gallery'
      path: '/gallery'
      fullPath: '/admin/website/gallery'
      preLoaderRoute: typeof AdminWebsiteGalleryRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/homepage': {
      id: '/admin/website/homepage'
      path: '/homepage'
      fullPath: '/admin/website/homepage'
      preLoaderRoute: typeof AdminWebsiteHomepageRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/seo': {
      id: '/admin/website/seo'
      path: '/seo'
      fullPath: '/admin/website/seo'
      preLoaderRoute: typeof AdminWebsiteSeoRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/services': {
      id: '/admin/website/services'
      path: '/services'
      fullPath: '/admin/website/services'
      preLoaderRoute: typeof AdminWebsiteServicesRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
    '/admin/website/testimonials': {
      id: '/admin/website/testimonials'
      path: '/testimonials'
      fullPath: '/admin/website/testimonials'
      preLoaderRoute: typeof AdminWebsiteTestimonialsRouteImport
      parentRoute: typeof AdminWebsiteRoute
    }
  }
}

interface AdminWebsiteRouteChildren {
  AdminWebsiteCompanyInfoRoute: typeof AdminWebsiteCompanyInfoRoute
  AdminWebsiteFaqsRoute: typeof AdminWebsiteFaqsRoute
  AdminWebsiteGalleryRoute: typeof AdminWebsiteGalleryRoute
  AdminWebsiteHomepageRoute: typeof AdminWebsiteHomepageRoute
  AdminWebsiteSeoRoute: typeof AdminWebsiteSeoRoute
  AdminWebsiteServicesRoute: typeof AdminWebsiteServicesRoute
  AdminWebsiteTestimonialsRoute: typeof AdminWebsiteTestimonialsRoute
}

const AdminWebsiteRouteChildren: AdminWebsiteRouteChildren = {
  AdminWebsiteCompanyInfoRoute: AdminWebsiteCompanyInfoRoute,
  AdminWebsiteFaqsRoute: AdminWebsiteFaqsRoute,
  AdminWebsiteGalleryRoute: AdminWebsiteGalleryRoute,
  AdminWebsiteHomepageRoute: AdminWebsiteHomepageRoute,
  AdminWebsiteSeoRoute: AdminWebsiteSeoRoute,
  AdminWebsiteServicesRoute: AdminWebsiteServicesRoute,
  AdminWebsiteTestimonialsRoute: AdminWebsiteTestimonialsRoute,
}

const AdminWebsiteRouteWithChildren = AdminWebsiteRoute._addFileChildren(
  AdminWebsiteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HealthRoute: HealthRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  TermsRoute: TermsRoute,
  TestEnvRoute: TestEnvRoute,
  TradeRoute: TradeRoute,
  TravelRoute: TravelRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDebugRoute: AdminDebugRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminWebsiteRoute: AdminWebsiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
